name: Update Publications

on:
  schedule:
    - cron: "0 0 * * 1" # Runs weekly on Monday
  workflow_dispatch:

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch Publications
        run: python scripts/fetch_publications.py

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add _publications/
          git commit -m "Update publications"
        continue-on-error: true # Avoid failing if no changes

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
